eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 7003
spring:
  application:
    name: service-feign
#高版本SpringCloud默认开启hyStrix断路器，如果没有开启，手动开启，不需要导依赖
feign:
  hystrix:
    enabled: true